/* eslint-disable @typescript-eslint/explicit-function-return-type */

/* global addToLibrary */

const LibraryWebGPUExtensions = {
    wgpuWagyuAdapterGetBackend: undefined,
    wgpuWagyuAdapterGetExtensions: undefined,
    wgpuWagyuAdapterGetGraphicsReport: undefined,
    wgpuWagyuAdapterGetName: undefined,
    wgpuWagyuAdapterRequestDeviceSync: undefined,
    wgpuWagyuCommandEncoderBlit: undefined,
    wgpuWagyuCommandEncoderExecuteCallback: undefined,
    wgpuWagyuCommandEncoderGenerateMipmap: undefined,
    wgpuWagyuComputePassEncoderExecuteCallback: undefined,
    wgpuWagyuDeviceClearPipelineBinaryCache: undefined,
    wgpuWagyuDeviceEnableImaginationWorkarounds: undefined,
    wgpuWagyuDeviceFlush: undefined,
    wgpuWagyuDeviceGetExtensions: undefined,
    wgpuWagyuDeviceImportExternalTexture: undefined,
    wgpuWagyuDeviceIntrospectShaderCode: undefined,
    wgpuWagyuDevicePipelineBinaryCacheStatistics: undefined,
    wgpuWagyuDevicePopulatePipelineBinaryCache: undefined,
    wgpuWagyuDeviceSetPipelineBinaryCallback: undefined,
    wgpuWagyuDeviceSetPipelineBinaryErrorCallback: undefined,
    wgpuWagyuExternalTextureAddRef: undefined,
    wgpuWagyuExternalTextureGetInfo: undefined,
    wgpuWagyuExternalTextureRelease: undefined,
    wgpuWagyuExternalTextureSetLabel: undefined,
    wgpuWagyuInstanceEnableImaginationWorkarounds: undefined,
    wgpuWagyuInstanceGetApiVersion: undefined,
    wgpuWagyuInstanceGetBackend: undefined,
    wgpuWagyuInstanceGetExposedWgslFeatures: undefined,
    wgpuWagyuInstanceGetScreenDirectFormat: undefined,
    wgpuWagyuInstanceGetScreenIndirectFormat: undefined,
    wgpuWagyuInstanceGetSync: undefined,
    wgpuWagyuInstanceRequestAdapterSync: undefined,
    wgpuWagyuInstanceSetCommandBufferLimit: undefined,
    wgpuWagyuInstanceSetExposedWgslFeatures: undefined,
    wgpuWagyuInstanceSetImmediate: undefined,
    wgpuWagyuInstanceSetRunBarriersOnIncoherent: undefined,
    wgpuWagyuInstanceSetStagingBufferCacheSize: undefined,
    wgpuWagyuInstanceSetSync: undefined,
    wgpuWagyuQueueCopyExternalImageToTexture: undefined,
    wgpuWagyuRenderBundleEncoderClearColorAttachments: undefined,
    wgpuWagyuRenderBundleEncoderClearDepthAttachment: undefined,
    wgpuWagyuRenderBundleEncoderClearPixelLocalStorage: undefined,
    wgpuWagyuRenderBundleEncoderClearStencilAttachment: undefined,
    wgpuWagyuRenderBundleEncoderExecuteCallback: undefined,
    wgpuWagyuRenderBundleEncoderSetScissorRect: undefined,
    wgpuWagyuRenderBundleEncoderSetScissorRectIndirect: undefined,
    wgpuWagyuRenderBundleEncoderSetViewport: undefined,
    wgpuWagyuRenderBundleEncoderSetViewportWithDepthIndirect: undefined,
    wgpuWagyuRenderBundleEncoderSetViewportWithoutDepthIndirect: undefined,
    wgpuWagyuRenderPassEncoderClearColorAttachments: undefined,
    wgpuWagyuRenderPassEncoderClearDepthAttachment: undefined,
    wgpuWagyuRenderPassEncoderClearPixelLocalStorage: undefined,
    wgpuWagyuRenderPassEncoderClearStencilAttachment: undefined,
    wgpuWagyuRenderPassEncoderExecuteBundle: undefined,
    wgpuWagyuRenderPassEncoderExecuteCallback: undefined,
    wgpuWagyuRenderPassEncoderSetShaderPixelLocalStorageEnabled: undefined,
    wgpuWagyuShaderEntryPointArrayFreeMembers: undefined,
    wgpuWagyuShaderModuleDestroy: undefined,
    wgpuWagyuShaderModuleEntryPoints: undefined,
    wgpuWagyuShaderModuleIntrospect: undefined,
    wgpuWagyuStringArrayFreeMembers: undefined,
    wgpuWagyuSurfaceDestroy: undefined,
    wgpuWagyuSurfaceGetCurrentDepthStencilTexture: undefined,
    wgpuWagyuSurfaceGetHeight: undefined,
    wgpuWagyuSurfaceGetWidth: undefined,
    wgpuWagyuSurfaceGetX: undefined,
    wgpuWagyuSurfaceGetY: undefined,
    wgpuWagyuSurfacePresent: undefined,
    wgpuWagyuSurfaceSetHeight: undefined,
    wgpuWagyuSurfaceSetWidth: undefined,
    wgpuWagyuSurfaceSetX: undefined,
    wgpuWagyuSurfaceSetY: undefined,
    wgpuWagyuTextureIsSwapchain: undefined,
    wgpuWagyuTextureReadPixels: undefined,
    wgpuWagyuWGSLFeatureTypeArrayFreeMembers: undefined
};

addToLibrary(LibraryWebGPUExtensions);
