#include "/Engine/Public/Platform.ush"

#if !SOURCE_TEXTURE_MSAA
#undef SOURCE_TEXTURE_MSAA
#endif

#include "parse_environment.ush"
#include "Generated/rhi.minified.ush"

#ifdef UNIFORM_DEFINITIONS_AUTO_GENERATED
#include "/Engine/Private/Common.ush"
#else
#include "flush_uniforms.minified.ush"
#include "image_draw_uniforms.minified.ush"
#endif

#include "Generated/constants.minified.ush"
#include "Generated/common.minified.ush"
#include "Generated/blit_texture_as_draw.minified.ush"
