#define ENABLE_INSTANCE_INDEX
#define PLS_IMPL_SUBPASS_LOAD
#define OPTIONALLY_FLAT flat
#define DRAW_IMAGE

#include "/Engine/Public/Platform.ush"
#ifdef UNIFORM_DEFINITIONS_AUTO_GENERATED
#include "/Engine/Generated/GeneratedUniformBuffers.ush"
#endif

#include "glsl.minified.glsl"
#include "constants.minified.glsl"
#include "specialization.minified.glsl"
#include "common.minified.glsl"
#include "advanced_blend.minified.glsl"
#include "draw_clockwise_image_mesh.minified.glsl"
