#define ENABLE_BASE_VERTEX 1
#define OPTIONALLY_FLAT flat
#define RENDER_MODE_DEPTH_STENCIL 1

#define DRAW_PATH 1

#if ENABLE_CLIP_RECT
#define NEEDS_CLIP_DISTANCE 1
#endif

#include "parse_environment.ush"
#include "Generated/rhi.minified.ush"

#ifdef UNIFORM_DEFINITIONS_AUTO_GENERATED
#include "/Engine/Private/Common.ush"
#else
#include "flush_uniforms.minified.ush"
#endif

#include "Generated/constants.minified.ush"
#include "Generated/common.minified.ush"
#include "Generated/draw_path_common.minified.ush"
#include "Generated/advanced_blend.minified.ush"
#include "Generated/gradient_packing_common.minified.ush"
#include "Generated/draw_depthstencil_path.minified.ush"
