#include "/Engine/Public/Platform.ush"
#define SPLIT_UINT4_ATTRIBUTES 1

#include "parse_environment.ush"
#include "Generated/rhi.minified.ush"

#ifdef UNIFORM_DEFINITIONS_AUTO_GENERATED
#include "/Engine/Private/Common.ush"
#else
#include "flush_uniforms.minified.ush"
#endif

#include "Generated/constants.minified.ush"
#include "Generated/common.minified.ush"
#include "Generated/bezier_utils.minified.ush"
#include "Generated/tessellate.minified.ush"
