#include "rive/artboard.hpp"
#include "rive/layout/grid_item_placement.hpp"
#include "rive/layout_component.hpp"
#include "rive/viewmodel/runtime/viewmodel_instance_number_runtime.hpp"
#include "rive/viewmodel/runtime/viewmodel_instance_runtime.hpp"
#include "rive/viewmodel/runtime/viewmodel_runtime.hpp"
#include "rive_file_reader.hpp"
#include "rive_testing.hpp"
#include <catch.hpp>

// Grid placement is the first bindable property backed by a *signed* core
// field. CoreIntType shares CoreUintType's field id, so the data bind paths
// can't tell the two apart from propertyFieldId alone — they ask
// CoreRegistry::isSignedInt and route through setInt. Bind through setUint
// instead and the write silently does nothing, and negatives clamp to 0.
//
// Asset generated by rive_core/test/grid_item_placement_bind_export_test.dart:
// a 200x100 artboard with a display:grid layout, template columns
// [100px, 100px], template rows [50px, 50px], and one fill cell whose
// GridItemPlacement has gridColumn bound to view model number "column" and
// gridColumnSpan bound to "span".
TEST_CASE("a bound grid placement drives the layout", "[layoutgrid]")
{
    auto file = ReadRiveFile("assets/layout/grid_placement_bound.riv");
    auto artboard = file->artboard()->instance();
    REQUIRE(artboard != nullptr);

    auto viewModel = file->viewModelByName("vm");
    REQUIRE(viewModel != nullptr);
    auto viewModelInstance = viewModel->createDefaultInstance();
    REQUIRE(viewModelInstance != nullptr);
    artboard->bindViewModelInstance(viewModelInstance->instance());

    auto column = viewModelInstance->propertyNumber("column");
    auto span = viewModelInstance->propertyNumber("span");
    REQUIRE(column != nullptr);
    REQUIRE(span != nullptr);

    // The only item carrying explicit placement; names don't survive export.
    rive::LayoutComponent* cell = nullptr;
    for (auto layout : artboard->find<rive::LayoutComponent>())
    {
        if (!layout->is<rive::Artboard>() &&
            rive::GridItemPlacement::from(layout) != nullptr)
        {
            cell = layout;
        }
    }
    REQUIRE(cell != nullptr);

    SECTION("a bound span widens the item")
    {
        span->value(2.0f);
        artboard->advance(0.0f);

        // Two 100px columns; a span of 2 covers both.
        REQUIRE(cell->layoutWidth() == 200.0f);
    }

    SECTION("a bound column places the item")
    {
        column->value(2.0f);
        span->value(1.0f);
        artboard->advance(0.0f);

        REQUIRE(cell->layoutX() == 100.0f);
        REQUIRE(cell->layoutWidth() == 100.0f);
    }

    SECTION("a negative bound column counts back from the last cell")
    {
        // The signed case: -1 is end-relative. Routed through setUint this
        // clamps to 0 and the item lands in column 1 instead.
        column->value(-1.0f);
        span->value(1.0f);
        artboard->advance(0.0f);

        REQUIRE(cell->layoutX() == 100.0f);
    }
}
