/*
 * Copyright 2026 Rive
 */

// A listener action run by a state or a transition can write a view model
// value that the same state machine's transition conditions read. The machine
// evaluates those conditions against its own bound copies of the values, so
// they have to be synced right after the action runs; otherwise the next
// condition check, in the same advance, sees the value from before the write.
//
// assets/state_action_vm_sync.riv is generated by
// packages/rive_core/test/generate_state_action_vm_sync_riv_test.dart. Both
// artboards have one layer, "Router", whose any state returns it to `idle`
// while the view model's `ready` is false. That guard is checked first, so a
// stale `ready` makes it win over the transition the write unlocks.

#include "rive/animation/animation_state.hpp"
#include "rive/animation/linear_animation.hpp"
#include "rive/animation/state_machine_instance.hpp"
#include "rive/file.hpp"
#include "rive/viewmodel/viewmodel_instance_boolean.hpp"
#include "rive/viewmodel/viewmodel_instance_trigger.hpp"
#include "rive_file_reader.hpp"
#include <catch.hpp>

using namespace rive;

namespace
{
struct RouterScene
{
    rcp<File> file;
    std::unique_ptr<ArtboardInstance> artboard;
    std::unique_ptr<StateMachineInstance> machine;
    rcp<ViewModelInstance> viewModel;

    explicit RouterScene(const char* artboardName)
    {
        file = ReadRiveFile("assets/state_action_vm_sync.riv");
        artboard = file->artboardNamed(artboardName);
        REQUIRE(artboard != nullptr);
        machine = artboard->stateMachineAt(0);
        REQUIRE(machine != nullptr);
        viewModel = file->createViewModelInstance(artboard->viewModelId(), 0);
        REQUIRE(viewModel != nullptr);
        machine->bindViewModelInstance(viewModel);
        machine->advanceAndApply(0.0f);
    }

    std::string state()
    {
        auto layerState = machine->layerState(0);
        if (layerState == nullptr || !layerState->is<AnimationState>())
        {
            return "";
        }
        auto animation = layerState->as<AnimationState>()->animation();
        return animation == nullptr ? "" : animation->name();
    }

    bool ready()
    {
        return viewModel->propertyValue("ready")
            ->as<ViewModelInstanceBoolean>()
            ->propertyValue();
    }

    void fireGo()
    {
        viewModel->propertyValue("go")
            ->as<ViewModelInstanceTrigger>()
            ->trigger();
    }
};
} // namespace

TEST_CASE("a state's enter action write is visible to the next transition "
          "check in the same advance",
          "[state_machine][data_bind]")
{
    RouterScene scene("StateEnter");
    CHECK(scene.state() == "idle");
    CHECK_FALSE(scene.ready());

    // any -> ready takes the trigger; ready's enter action sets `ready`, which
    // must block any -> idle and allow ready -> done before the frame ends.
    scene.fireGo();
    scene.machine->advanceAndApply(0.016f);
    CHECK(scene.ready());
    CHECK(scene.state() == "done");
}

TEST_CASE("a timed transition's end action write is visible to the next "
          "transition check in the same advance",
          "[state_machine][data_bind]")
{
    RouterScene scene("TransitionEnd");
    CHECK(scene.state() == "idle");

    // idle -> mid takes the trigger and mixes for 100ms.
    scene.fireGo();
    scene.machine->advanceAndApply(0.016f);
    CHECK(scene.state() == "mid");
    CHECK_FALSE(scene.ready());

    // The mix completes in updateMix, whose end action sets `ready` just
    // before the layer's first transition check of that advance.
    for (int i = 0; i < 10; i++)
    {
        scene.machine->advanceAndApply(0.016f);
    }
    CHECK(scene.ready());
    CHECK(scene.state() == "done");
}
