#define AlignedBuffer r_0
#define BlendModeRiveToPLS r_1
#define BufferGL r_2
#define BufferRing r_3
#define BufferRingShadowImpl r_4
#define BytesPerPixel r_5
#define CalcPolarSegmentsPerRadian r_6
#define ChopCubicAt r_7
#define ClipElement r_8
#define ClipRectInverseMatrix r_9
#define ColorRampPipeline r_a
#define ContourData r_b
#define DeepHashGradient r_c
#define Dirt r_d
#define Draw r_e
#define DrawPipeline r_f
#define DrawProgram r_10
#define DrawShader r_11
#define DrawType r_12
#define Empty r_13
#define EvalCubicAt r_14
#define Filter r_15
#define FindCubicConvex180Chops r_16
#define FindSubdivisionCount r_17
#define FindTransformedArea r_18
#define FixedQueue r_19
#define FlushDescriptor r_1a
#define FlushType r_1b
#define FlushUniforms r_1c
#define Format r_1d
#define FrameDescriptor r_1e
#define GLState r_1f
#define GPUResourceLimits r_20
#define GeneratePatchBufferData r_21
#define GetShaderFeatureGLSLName r_22
#define GradientContentKey r_23
#define GradientLibrary r_24
#define GradientSpan r_25
#define HeapBufferRing r_26
#define ImageMeshUniforms r_27
#define InteriorTriangulationHelper r_28
#define IsAABB r_29
#define Iter r_2a
#define JoinTypeFlags r_2b
#define LoadAction r_2c
#define MakeClipUpdate r_2d
#define MakeColor r_2e
#define MakeContext r_2f
#define MakeGradient r_30
#define MakeImage r_31
#define MakePLSImplEXTNative r_32
#define MakePLSImplFramebufferFetch r_33
#define MakePLSImplRWTexture r_34
#define MakePLSImplWebGL r_35
#define MaxPathID r_36
#define MeasureAngleBetweenVectors r_37
#define Node r_38
#define PLSBlendMode r_39
#define PLSFactory r_3a
#define PLSGradDataArray r_3b
#define PLSGradient r_3c
#define PLSImage r_3d
#define PLSImpl r_3e
#define PLSImplEXTNative r_3f
#define PLSImplFramebufferFetch r_40
#define PLSImplRWTexture r_41
#define PLSImplWebGL r_42
#define PLSPaint r_43
#define PLSPath r_44
#define PLSRenderBufferGLImpl r_45
#define PLSRenderContext r_46
#define PLSRenderContextGLImpl r_47
#define PLSRenderContextHelperImpl r_48
#define PLSRenderContextImpl r_49
#define PLSRenderContextMetalImpl r_4a
#define PLSRenderTarget r_4b
#define PLSRenderTargetGL r_4c
#define PLSRenderTargetMetal r_4d
#define PLSRenderer r_4e
#define PLSTexture r_4f
#define PLSTextureGLImpl r_50
#define PaddingToAlignUp r_51
#define PaintData r_52
#define PaintType r_53
#define PatchBaseIndex r_54
#define PatchIndexCount r_55
#define PatchSegmentSpan r_56
#define PatchType r_57
#define PatchVertex r_58
#define PathData r_59
#define PathDraw r_5a
#define PathOp r_5b
#define PerFlushLinkedList r_5c
#define PlatformFeatures r_5d
#define RenderState r_5e
#define ShaderFeatures r_5f
#define ShaderUniqueKey r_60
#define StyledVerb r_61
#define TessVertexCounter r_62
#define TessVertexSpan r_63
#define TessellatePipeline r_64
#define TexelBufferGL r_65
#define TexelBufferRing r_66
#define TriangleVertex r_67
#define TwoTexelRamp r_68
#define WideOpen r_69
#define WriteOnlyMappedMemory r_6a
#define accumulateMax r_6b
#define activatePixelLocalStorage r_6c
#define addRenderPath r_6d
#define advanced_blend r_6e
#define allocateBackingTexture r_6f
#define allocateCoverageBackingTextures r_70
#define allocateGPUResources r_71
#define applyClip r_72
#define attachTexturesToCurrentFramebuffer r_73
#define avoidFlatVaryings r_74
#define barrier r_75
#define baseElement r_76
#define baseInstancePolyfillLocation r_77
#define bindBuffer r_78
#define bindProgram r_79
#define bindVAO r_7a
#define bits_equal r_7b
#define blendMode r_7c
#define bytesWritten r_7d
#define canMapBuffer r_7e
#define can_combine_draw_images r_7f
#define cap r_80
#define capacity r_81
#define chop_cubic_around_cusps r_82
#define chop_key r_83
#define clipID r_84
#define clipRect r_85
#define clipRectInverseMatrix r_86
#define clipRectMatrix r_87
#define clipStackHeight r_88
#define closed r_89
#define coeffs r_8a
#define color r_8b
#define color1 r_8c
#define colorData r_8d
#define colorIfColor r_8e
#define color_ramp r_8f
#define colors r_90
#define common r_91
#define complexGradRowsHeight r_92
#define complexGradRowsTop r_93
#define complexGradSpanCount r_94
#define constants r_95
#define contourBufferRing r_96
#define contourCount r_97
#define contourIDWithFlags r_98
#define convert_line_to_cubic r_99
#define count r_9a
#define countPath r_9b
#define createSideFramebuffer r_9c
#define cusp_chop_key r_9d
#define data r_9e
#define deactivatePixelLocalStorage r_9f
#define decodeImage r_a0
#define decodeImageTexture r_a1
#define deleteBuffer r_a2
#define deleteProgram r_a3
#define deleteVAO r_a4
#define detachBuffers r_a5
#define drawFramebufferID r_a6
#define drawImageMesh r_a7
#define drawList r_a8
#define drawType r_a9
#define draw_image_mesh r_aa
#define draw_path r_ab
#define elementCount r_ac
#define emplace_back r_ad
#define empty r_ae
#define empty_stroke_cap r_af
#define enableFaceCulling r_b0
#define endCurveIdx r_b1
#define endLineIdx r_b2
#define endOfContour r_b3
#define endRotationIdx r_b4
#define ensureRasterOrderingEnabled r_b5
#define fillCoverage r_b6
#define fillRule r_b7
#define fillsDisabled r_b8
#define filter_gl r_b9
#define find_cubic_tan0 r_ba
#define find_cubic_tan1 r_bb
#define find_cubic_tangents r_bc
#define find_ending_tangent r_bd
#define find_join_tangent r_be
#define find_join_tangent_full_impl r_bf
#define find_starting_tangent r_c0
#define firstContourIdx r_c1
#define flags r_c2
#define flushUniformBufferRing r_c3
#define format_gl r_c4
#define frameDescriptor r_c5
#define freeBuffer r_c6
#define generateClipID r_c7
#define generate_buffer_data_for_patch_type r_c8
#define getBlendMode r_c9
#define getBounds r_ca
#define getCap r_cb
#define getClipContentID r_cc
#define getColor r_cd
#define getFillRule r_ce
#define getFlushCount r_cf
#define getGradient r_d0
#define getImageOpacity r_d1
#define getImageTexture r_d2
#define getIsStroked r_d3
#define getJoin r_d4
#define getRawPath r_d5
#define getTexture r_d6
#define getThickness r_d7
#define getType r_d8
#define getUniqueID r_d9
#define gl_buffer_id r_da
#define glsl r_db
#define gpu r_dc
#define gradSpanBufferRing r_dd
#define gradTextureInverseHeight r_de
#define gradient r_df
#define gradientTextureHeight r_e0
#define growExceededGPUResources r_e1
#define hasClipRect r_e2
#define hasRoomFor r_e3
#define hasTriangleVertices r_e4
#define heap_buffer_contents r_e5
#define horizontalSpan r_e6
#define ignore r_e7
#define image r_e8
#define imageMeshUniformBufferRing r_e9
#define imageTextureRef r_ea
#define impl r_eb
#define internalformat_gl r_ec
#define invalidateStroke r_ed
#define inverseViewports r_ee
#define invertOffscreenY r_ef
#define isEquivalent r_f0
#define is_final_verb_of_contour r_f1
#define itemSizeInBytes r_f2
#define joinTangent r_f3
#define kBevelJoin r_f4
#define kBufferRingSize r_f5
#define kClipPlaneIdx r_f6
#define kContourIDMask r_f7
#define kContourTexelsPerItem r_f8
#define kContourTextureIdx r_f9
#define kContourTextureWidthInItems r_fa
#define kContourTextureWidthInTexels r_fb
#define kCoveragePlaneIdx r_fc
#define kCullExcessTessellationSegments r_fd
#define kEmulatedStrokeCap r_fe
#define kEvenOdd r_ff
#define kFanMidpointVertex r_100
#define kFanVertex r_101
#define kFramebufferPlaneIdx r_102
#define kGPUResourceIntermediateGrowthFactor r_103
#define kGPUResourcePadding r_104
#define kGradTextureIdx r_105
#define kGradTextureWidth r_106
#define kGradTextureWidthInSimpleRamps r_107
#define kGradient r_108
#define kImageMeshShaderFeaturesMask r_109
#define kImageTextureIdx r_10a
#define kJoinSegmentCount r_10b
#define kJoinTypeMask r_10c
#define kLargestDenormalizedFP16 r_10d
#define kLargestFP16BeforeExponentAll1s r_10e
#define kMaxComplexGradients r_10f
#define kMaxContourID r_110
#define kMaxCurveSubdivisions r_111
#define kMaxGradTextureHeight r_112
#define kMaxParametricSegments r_113
#define kMaxPolarSegments r_114
#define kMaxSimpleColorRampRows r_115
#define kMaxTessTextureHeight r_116
#define kMaxTessellationVertexCount r_117
#define kMidpointFanPatchBaseIndex r_118
#define kMidpointFanPatchIndexCount r_119
#define kMidpointFanPatchSegmentSpan r_11a
#define kMidpointFanPatchVertexCount r_11b
#define kMinComplexGradients r_11c
#define kMinGradTextureHeight r_11d
#define kMinSimpleColorRampRows r_11e
#define kMinTessTextureHeight r_11f
#define kMiterClipJoin r_120
#define kMiterRevertJoin r_121
#define kNumSegmentsInMiterOrBevelJoin r_122
#define kOriginalDstColorPlaneIdx r_123
#define kOuterCurvePatchBaseIndex r_124
#define kOuterCurvePatchIndexCount r_125
#define kOuterCurvePatchSegmentSpan r_126
#define kOuterCurvePatchVertexCount r_127
#define kPLSDrawBuffers r_128
#define kParametricPrecision r_129
#define kPatchIndexBufferCount r_12a
#define kPatchSegmentCountExcludingJoin r_12b
#define kPatchVertexBufferCount r_12c
#define kPathTexelsPerItem r_12d
#define kPathTextureIdx r_12e
#define kPathTextureWidthInItems r_12f
#define kPathTextureWidthInTexels r_130
#define kPerFlushAllocatorInitialBlockSize r_131
#define kPolarPrecision r_132
#define kRadialGradient r_133
#define kRetrofittedTriangle r_134
#define kRoundJoinStyleFlag r_135
#define kShaderFeatureCount r_136
#define kShaderVersionStringBuffSize r_137
#define kStrokeStyleFlag r_138
#define kStrokeVertex r_139
#define kTessTextureWidth r_13a
#define kTessTextureWidthLog2 r_13b
#define kTessVertexTextureIdx r_13c
#define kVertexShaderFeaturesMask r_13d
#define localVertexID r_13e
#define m_activeTextureIdx r_13f
#define m_baseInstancePolyfillLocation r_140
#define m_blendMode r_141
#define m_boundArrayBuffer r_142
#define m_boundPixelUnpackBuffer r_143
#define m_boundProgramID r_144
#define m_boundUniformBuffer r_145
#define m_boundVAO r_146
#define m_bounds r_147
#define m_buffer r_148
#define m_bufferIDs r_149
#define m_bufferRingIdx r_14a
#define m_bufferRingLocks r_14b
#define m_cachedUniformData r_14c
#define m_cap r_14d
#define m_capacity r_14e
#define m_chops r_14f
#define m_clipContentID r_150
#define m_clipMemorylessTexture r_151
#define m_clipStack r_152
#define m_clipStackFlushID r_153
#define m_clipTextureID r_154
#define m_coeffs r_155
#define m_color r_156
#define m_colorRampFBO r_157
#define m_colorRampPipeline r_158
#define m_colorRampProgram r_159
#define m_colorRampVAO r_15a
#define m_colors r_15b
#define m_complexGradients r_15c
#define m_contents r_15d
#define m_context r_15e
#define m_contourBatch r_15f
#define m_contourBuffer r_160
#define m_contourData r_161
#define m_count r_162
#define m_coverageMemorylessTexture r_163
#define m_coverageTextureID r_164
#define m_current r_165
#define m_currentContourID r_166
#define m_currentContourPaddingVertexCount r_167
#define m_currentFrameResourceUsage r_168
#define m_currentPathID r_169
#define m_currentPathIsStroked r_16a
#define m_currentPathNeedsMirroredContours r_16b
#define m_currentResourceLimits r_16c
#define m_data r_16d
#define m_dirt r_16e
#define m_drawFramebufferID r_16f
#define m_drawList r_170
#define m_drawPipelines r_171
#define m_drawPrograms r_172
#define m_drawVAO r_173
#define m_end r_174
#define m_capabilities r_175
#define m_faceCullingEnabled r_176
#define m_fallbackMappedMemory r_177
#define m_fillRule r_178
#define m_flushCount r_179
#define m_flushUniformBuffer r_17a
#define m_format r_17b
#define m_frameDescriptor r_17c
#define m_front r_17d
#define m_gpu r_17e
#define m_gradSpanBuffer r_17f
#define m_gradSpanData r_180
#define m_gradient r_181
#define m_gradientTexture r_182
#define m_head r_183
#define m_height r_184
#define m_id r_185
#define m_ids r_186
#define m_imageMeshUniformBuffer r_187
#define m_imageMeshUniformData r_188
#define m_imageMeshVAO r_189
#define m_imageOpacity r_18a
#define m_imageTexture r_18b
#define m_impl r_18c
#define m_initialTessVertexCount r_18d
#define m_interiorTrianglesVAO r_18e
#define m_internalPathBatch r_18f
#define m_inverseMatrix r_190
#define m_isFirstFlushOfFrame r_191
#define m_itemSizeInBytes r_192
#define m_join r_193
#define m_lastGeneratedClipID r_194
#define m_localData r_195
#define m_mappedMemory r_196
#define m_mappingEnd r_197
#define m_maxPathID r_198
#define m_maxRecentResourceUsage r_199
#define m_maxTriangleVertexCount r_19a
#define m_mirroredTessLocation r_19b
#define m_nextMappedItem r_19c
#define m_numChops r_19d
#define m_offscreenTextureID r_19e
#define m_originalDstColorMemorylessTexture r_19f
#define m_originalDstColorTextureID r_1a0
#define m_ownsDrawFramebuffer r_1a1
#define m_paintType r_1a2
#define m_parametricSegmentCounts r_1a3
#define m_parametricSegmentCounts_pow4 r_1a4
#define m_patchCount r_1a5
#define m_patchIndicesBuffer r_1a6
#define m_patchVerticesBuffer r_1a7
#define m_pathBuffer r_1a8
#define m_pathData r_1a9
#define m_pathPatchIndexBuffer r_1aa
#define m_pathPatchVertexBuffer r_1ab
#define m_pixelFormat r_1ac
#define m_platformFeatures r_1ad
#define m_plsImpl r_1ae
#define m_plsLibrary r_1af
#define m_polarSegmentCounts r_1b0
#define m_queue r_1b1
#define m_rasterOrderingEnabled r_1b2
#define m_rawPath r_1b3
#define m_reservedSimpleGradientRowCount r_1b4
#define m_runningTessVertexCount r_1b5
#define m_scratchPath r_1b6
#define m_shaderVersionString r_1b7
#define m_shadowBuffer r_1b8
#define m_sideFramebufferID r_1b9
#define m_simpleColorRampsBuffer r_1ba
#define m_simpleColorRampsData r_1bb
#define m_simpleGradients r_1bc
#define m_stack r_1bd
#define m_state r_1be
#define m_stops r_1bf
#define m_stroked r_1c0
#define m_submittedBufferIdx r_1c1
#define m_tail r_1c2
#define m_tangentPairs r_1c3
#define m_target r_1c4
#define m_targetTexture r_1c5
#define m_tessPipeline r_1c6
#define m_tessSpanBuffer r_1c7
#define m_tessSpanData r_1c8
#define m_tessVertexCount r_1c9
#define m_tessVertexTexture r_1ca
#define m_tessellateFBO r_1cb
#define m_tessellateProgram r_1cc
#define m_tessellateVAO r_1cd
#define m_texelsPerItem r_1ce
#define m_texture r_1cf
#define m_thickness r_1d0
#define m_triangleBuffer r_1d1
#define m_trivialPerFlushAllocator r_1d2
#define m_uniqueID r_1d3
#define m_vertexShaders r_1d4
#define m_width r_1d5
#define m_widthInItems r_1d6
#define makeImageTexture r_1d7
#define makeLinearGradient r_1d8
#define makeOffscreenRenderTarget r_1d9
#define makePixelUnpackBufferRing r_1da
#define makeRadialGradient r_1db
#define makeRenderBuffer r_1dc
#define makeRenderTarget r_1dd
#define makeScaled r_1de
#define makeScaledIfLarger r_1df
#define makeTexelBufferRing r_1e0
#define makeUniformBufferRing r_1e1
#define makeVertexBufferRing r_1e2
#define make_memoryless_pls_texture r_1e3
#define make_pipeline_state r_1e4
#define mapBuffer r_1e5
#define mapContourTexture r_1e6
#define mapFlushUniformBuffer r_1e7
#define mapGradSpanBuffer r_1e8
#define mapImageMeshUniformBuffer r_1e9
#define mapPathTexture r_1ea
#define mapSimpleColorRampsBuffer r_1eb
#define mapTessVertexSpanBuffer r_1ec
#define mapTriangleVertexBuffer r_1ed
#define matrix r_1ee
#define maxComplexGradientSpans r_1ef
#define maxContourID r_1f0
#define maxImageMeshUniforms r_1f1
#define maxPathID r_1f2
#define maxSimpleGradients r_1f3
#define maxTessellationSpans r_1f4
#define midpoint r_1f5
#define mirroredFillCoverage r_1f6
#define mirroredOutset r_1f7
#define mirroredVertexID r_1f8
#define needsClipBuffer r_1f9
#define next r_1fa
#define onBarrier r_1fb
#define onEnableRasterOrdering r_1fc
#define onMap r_1fd
#define onMapBuffer r_1fe
#define onUnmap r_1ff
#define onUnmapAndSubmitBuffer r_200
#define opacity r_201
#define opacityIfImage r_202
#define outerClipID r_203
#define outerClipIDIfClipUpdate r_204
#define outset r_205
#define pack_params r_206
#define padding r_207
#define padding0 r_208
#define padding1 r_209
#define paddingVertexCount r_20a
#define paint r_20b
#define paintData r_20c
#define paintRenderData r_20d
#define paintType r_20e
#define params r_20f
#define patchCount r_210
#define pathBounds r_211
#define pathBufferRing r_212
#define pathID r_213
#define pathIDGranularity r_214
#define pathUniqueID r_215
#define pathutils r_216
#define platformFeatures r_217
#define pls r_218
#define point r_219
#define pop_front_n r_21a
#define prepareToMapBuffers r_21b
#define processPath r_21c
#define pushContour r_21d
#define pushCubic r_21e
#define pushDraw r_21f
#define pushEmulatedStrokeCapAsJoinBeforeCubic r_220
#define pushGradient r_221
#define pushImageMesh r_222
#define pushImageMeshDraw r_223
#define pushInteriorTriangulation r_224
#define pushInternalPathBatchToContext r_225
#define pushMirroredTessellationSpans r_226
#define pushPaddingVertices r_227
#define pushPath r_228
#define pushPathDraw r_229
#define pushTessellationSpans r_22a
#define push_back_n r_22b
#define rawPath r_22c
#define refTexture r_22d
#define reflectionX0X1 r_22e
#define reflectionY r_22f
#define releaseRefs r_230
#define releaseTexture r_231
#define reserveImageMeshData r_232
#define reservePathData r_233
#define resetDrawList r_234
#define resetFlushTimeLimits r_235
#define resetGPUResources r_236
#define resetTexture r_237
#define resize r_238
#define resizeAndRewind r_239
#define resizeContourTexture r_23a
#define resizeGradSpanBuffer r_23b
#define resizeGradientTexture r_23c
#define resizeImageMeshUniformBuffer r_23d
#define resizePathTexture r_23e
#define resizeSimpleColorRampsBuffer r_23f
#define resizeTessVertexSpanBuffer r_240
#define resizeTessellationTexture r_241
#define resizeTriangleVertexBuffer r_242
#define resource_texture_height r_243
#define rive_pls_ios_metallib r_244
#define rive_pls_ios_metallib_len r_245
#define rive_pls_ios_simulator_metallib r_246
#define rive_pls_ios_simulator_metallib_len r_247
#define rive_pls_macosx_metallib r_248
#define rive_pls_macosx_metallib_len r_249
#define segmentCounts r_24a
#define set r_24b
#define setClipContentID r_24c
#define setMirroredPosition r_24d
#define setTargetTexture r_24e
#define set_back r_24f
#define shader r_250
#define shaderDefineName r_251
#define shaderFeatures r_252
#define shadowBuffer r_253
#define shrinkGPUResourcesToFit r_254
#define sideFramebufferID r_255
#define simpleColorRampsBufferRing r_256
#define simpleGradTexelsHeight r_257
#define simpleGradTexelsWidth r_258
#define simple_chop_key r_259
#define state r_25a
#define stops r_25b
#define strokeCapSegmentCount r_25c
#define strokeJoinCount r_25d
#define strokeMatrixMaxScale r_25e
#define strokeRadius r_25f
#define stroked r_260
#define strokesDisabled r_261
#define style r_262
#define style_flags r_263
#define styled_verb r_264
#define submitTexels r_265
#define submittedBufferID r_266
#define submittedBufferIdx r_267
#define submittedTextureID r_268
#define tail r_269
#define targetTexture r_26a
#define tessDataHeight r_26b
#define tessSpanBufferRing r_26c
#define tessVertexCount r_26d
#define tessVertexSpanCount r_26e
#define tessellate r_26f
#define tessellationTextureHeight r_270
#define thickness r_271
#define totalSizeInBytes r_272
#define totalVertexCountIncludingReflectionsAndPadding r_273
#define transform_rect_to_new_space r_274
#define triangleBufferRing r_275
#define triangleVertexBufferCount r_276
#define triangulator r_277
#define trivialPerFlushAllocator r_278
#define type_gl r_279
#define unmapAndSubmitBuffer r_27a
#define unmapContourTexture r_27b
#define unmapFlushUniformBuffer r_27c
#define unmapGradSpanBuffer r_27d
#define unmapImageMeshUniformBuffer r_27e
#define unmapPathTexture r_27f
#define unmapSimpleColorRampsBuffer r_280
#define unmapTessVertexSpanBuffer r_281
#define unmapTriangleVertexBuffer r_282
#define vertexDiscardValue r_283
#define vertexIndex0 r_284
#define weight_pathID r_285
#define widthInItems r_286
#define widthInTexels r_287
#define wireframe r_288
#define wrapGLRenderTarget r_289
#define x0x1 r_28a
