#define AlignedBuffer r_0
#define BlendTier r_1
#define BlendTierForBlendMode r_2
#define BufferRing r_3
#define BufferRingImpl r_4
#define BufferRingShadowImpl r_5
#define BytesPerPixel r_6
#define CalcPolarSegmentsPerRadian r_7
#define ChopCubicAt r_8
#define ClipElement r_9
#define ColorRampPipeline r_a
#define ColorRampUniforms r_b
#define ContourData r_c
#define CoverageBackingType r_d
#define DeepHashGradient r_e
#define DrawPipeline r_f
#define DrawProgram r_10
#define DrawShader r_11
#define DrawUniforms r_12
#define EvalCubicAt r_13
#define FindCubicConvex180Chops r_14
#define FixedQueue r_15
#define FlushType r_16
#define Format r_17
#define FrameDescriptor r_18
#define GenerateWedgeTriangles r_19
#define GradientContentKey r_1a
#define GradientLibrary r_1b
#define GradientSpan r_1c
#define IsAABB r_1d
#define JoinTypeFlag r_1e
#define LoadAction r_1f
#define MaxPathID r_20
#define MeasureAngleBetweenVectors r_21
#define PLSBlendMode r_22
#define PLSFactory r_23
#define PLSGradDataArray r_24
#define PLSGradient r_25
#define PLSPaint r_26
#define PLSPath r_27
#define PLSRenderContext r_28
#define PLSRenderContextESNative r_29
#define PLSRenderContextGL r_2a
#define PLSRenderContextMetal r_2b
#define PLSRenderTarget r_2c
#define PLSRenderTargetGL r_2d
#define PLSRenderTargetMetal r_2e
#define PLSRenderer r_2f
#define PaintData r_30
#define PaintType r_31
#define PathData r_32
#define PathDraw r_33
#define PathTextureHeight r_34
#define PlatformFeatures r_35
#define RenderState r_36
#define ShaderFeatures r_37
#define SourceType r_38
#define StyledVerb r_39
#define TessVertexSpan r_3a
#define TessellatePipeline r_3b
#define TessellateUniforms r_3c
#define TexelBufferGL r_3d
#define TexelBufferMetal r_3e
#define TexelBufferRing r_3f
#define TwoTexelRamp r_40
#define UniformBufferGL r_41
#define UniformBufferMetal r_42
#define UniformBufferRing r_43
#define VertexBufferGL r_44
#define VertexBufferMetal r_45
#define WedgeVertex r_46
#define activatePixelLocalStorage r_47
#define add r_48
#define addPaint r_49
#define addRenderPath r_4a
#define advanced_blend r_4b
#define allocateBackingTexture r_4c
#define allocateBackingTextures r_4d
#define applyClip r_4e
#define avoidFlatVaryings r_4f
#define bind r_50
#define bindCurrentBuffer r_51
#define bindToUniformBlock r_52
#define blendMode r_53
#define blendTier r_54
#define blend_mode_rive_to_pls r_55
#define bytesWritten r_56
#define cap r_57
#define capPolarSegmentCount r_58
#define capacity r_59
#define chop_cubic_around_cusps r_5a
#define chop_key r_5b
#define clipID r_5c
#define clipStackHeight r_5d
#define closed r_5e
#define coeffs r_5f
#define color r_60
#define color1 r_61
#define colorData r_62
#define color_ramp r_63
#define colors r_64
#define contentMatches r_65
#define contourBufferRing r_66
#define contourIDWithFlags r_67
#define convert_line_to_cubic r_68
#define count r_69
#define createDrawUniformBuffer r_6a
#define createReadFramebuffer r_6b
#define cusp_chop_key r_6c
#define data r_6d
#define deactivatePixelLocalStorage r_6e
#define decodeImage r_6f
#define draw r_70
#define drawFramebufferID r_71
#define drawImageMesh r_72
#define emplace_back r_73
#define empty r_74
#define enableEvenOdd r_75
#define enablePathClipping r_76
#define endCurveIdx r_77
#define endLineIdx r_78
#define endOfContour r_79
#define endRotationIdx r_7a
#define ensureMapped r_7b
#define fillCoverage r_7c
#define fillRule r_7d
#define fillsDisabled r_7e
#define find_cubic_tangents r_7f
#define find_final_control_point r_80
#define find_first_control_point r_81
#define find_join_tangent r_82
#define find_join_tangent_full_impl r_83
#define flags r_84
#define format_gl r_85
#define fragmentFeatures r_86
#define frameDescriptor r_87
#define generateClipID r_88
#define generatePreprocessorDefines r_89
#define getBlendMode r_8a
#define getCap r_8b
#define getClipContentID r_8c
#define getColor r_8d
#define getFillRule r_8e
#define getGradient r_8f
#define getIsStroked r_90
#define getJoin r_91
#define getRawPath r_92
#define getThickness r_93
#define getType r_94
#define glsl r_95
#define gpu r_96
#define gradSpanBufferRing r_97
#define gradTexelBufferRing r_98
#define gradient r_99
#define gradientLibrary r_9a
#define hasPendingColorRampsToRender r_9b
#define hasRoomFor r_9c
#define horizontalSpan r_9d
#define ignore r_9e
#define impl r_9f
#define internalformat_gl r_a0
#define invalidateStroke r_a1
#define isMidpoint r_a2
#define is_next_iter r_a3
#define itemSizeInBytes r_a4
#define joinCount r_a5
#define joinTangent r_a6
#define kBevelJoin r_a7
#define kBufferRingSize r_a8
#define kClipPlaneIdx r_a9
#define kContourIDMask r_aa
#define kContourTexelsPerItem r_ab
#define kContourTextureHeight r_ac
#define kContourTextureIdx r_ad
#define kContourTextureWidthInItems r_ae
#define kCoveragePlaneIdx r_af
#define kEvenOdd r_b0
#define kFirstVertexOfContour r_b1
#define kFramebufferPlaneIdx r_b2
#define kGradTextureHeight r_b3
#define kGradTextureIdx r_b4
#define kGradTextureWidth r_b5
#define kGradient r_b6
#define kLargestDenormalizedFP16 r_b7
#define kLargestFP16BeforeExponentAll1s r_b8
#define kMaxContourID r_b9
#define kMaxGradientSpans r_ba
#define kMaxParametricSegments r_bb
#define kMaxPolarSegments r_bc
#define kMaxTessVertexSpans r_bd
#define kMaxTessVertices r_be
#define kMiterJoin r_bf
#define kOriginalDstColorPlaneIdx r_c0
#define kParametricPrecision r_c1
#define kPathTexelsPerItem r_c2
#define kPathTextureIdx r_c3
#define kPathTextureWidthInItems r_c4
#define kPolarPrecision r_c5
#define kRadialGradient r_c6
#define kReservedRowsForSimpleRamps r_c7
#define kRoundJoinStyleFlag r_c8
#define kStrokeStyleFlag r_c9
#define kTessTextureHeight r_ca
#define kTessTextureWidth r_cb
#define kTessTextureWidthLog2 r_cc
#define kTessVertexTextureIdx r_cd
#define kWedgeIndexCount r_ce
#define kWedgeSize r_cf
#define kWedgeVertexCount r_d0
#define localVertexID r_d1
#define lockNextBufferRingIndex r_d2
#define m_activeTextureIdx r_d3
#define m_blendMode r_d4
#define m_buffer r_d5
#define m_bufferRingIdx r_d6
#define m_bufferRingLocks r_d7
#define m_buffers r_d8
#define m_cap r_d9
#define m_capacity r_da
#define m_chops r_db
#define m_clipContentID r_dc
#define m_clipMemorylessTexture r_dd
#define m_clipStack r_de
#define m_clipTextureID r_df
#define m_coeffs r_e0
#define m_color r_e1
#define m_colorRampFBO r_e2
#define m_colorRampPipeline r_e3
#define m_colorRampProgram r_e4
#define m_colorRampVAO r_e5
#define m_colors r_e6
#define m_complexGradients r_e7
#define m_context r_e8
#define m_contourBatch r_e9
#define m_contourBuffer r_ea
#define m_count r_eb
#define m_coverageMemorylessTexture r_ec
#define m_coverageTextureID r_ed
#define m_currentContourID r_ee
#define m_currentContourIDWithFlags r_ef
#define m_currentContourPaddingVertexCount r_f0
#define m_currentPathID r_f1
#define m_currentPathIsStroked r_f2
#define m_data r_f3
#define m_drawFramebufferID r_f4
#define m_drawPipelines r_f5
#define m_drawPrograms r_f6
#define m_drawUniformBuffer r_f7
#define m_drawVAO r_f8
#define m_end r_f9
#define m_fillRule r_fa
#define m_format r_fb
#define m_frameDescriptor r_fc
#define m_front r_fd
#define m_gpu r_fe
#define m_gradSpanBuffer r_ff
#define m_gradTexelBuffer r_100
#define m_gradient r_101
#define m_gradientLibrary r_102
#define m_hasArtboardClipCandidate r_103
#define m_height r_104
#define m_id r_105
#define m_ids r_106
#define m_impl r_107
#define m_isFirstFlushOfFrame r_108
#define m_itemSizeInBytes r_109
#define m_join r_10a
#define m_lastGeneratedClipID r_10b
#define m_localData r_10c
#define m_mappedMemory r_10d
#define m_mappingEnd r_10e
#define m_maxPathID r_10f
#define m_nextMappedItem r_110
#define m_numChops r_111
#define m_offscreenTextureID r_112
#define m_originalDstColorMemorylessTexture r_113
#define m_originalDstColorTextureID r_114
#define m_ownsDrawFramebuffer r_115
#define m_paintType r_116
#define m_parametricSegmentCounts r_117
#define m_parametricSegmentCounts_pow4 r_118
#define m_pathBatch r_119
#define m_pathBuffer r_11a
#define m_pathWedgeIndexBuffer r_11b
#define m_pathWedgeVertexBuffer r_11c
#define m_pixelFormat r_11d
#define m_platformFeatures r_11e
#define m_plsLibrary r_11f
#define m_polarSegmentCounts r_120
#define m_queue r_121
#define m_rawPath r_122
#define m_readFramebufferID r_123
#define m_shaderFeatures r_124
#define m_shadowBuffer r_125
#define m_simpleGradients r_126
#define m_stack r_127
#define m_stops r_128
#define m_stroked r_129
#define m_submittedBufferIdx r_12a
#define m_submittedComplexColorRampCount r_12b
#define m_submittedGradSpanCount r_12c
#define m_tangentPairs r_12d
#define m_targetTexture r_12e
#define m_tessPipeline r_12f
#define m_tessSpanBuffer r_130
#define m_tessVertexCount r_131
#define m_tessVertexTexture r_132
#define m_tessellateFBO r_133
#define m_tessellateProgram r_134
#define m_tessellateUniformBufferRing r_135
#define m_tessellateVAO r_136
#define m_texelsPerItem r_137
#define m_textures r_138
#define m_thickness r_139
#define m_uniformBuffer r_13a
#define m_vertexShaders r_13b
#define m_width r_13c
#define m_widthInItems r_13d
#define makeBufferF32 r_13e
#define makeBufferU16 r_13f
#define makeBufferU32 r_140
#define makeLinearGradient r_141
#define makeOffscreenRenderTarget r_142
#define makeRadialGradient r_143
#define makeRenderTarget r_144
#define make_cap r_145
#define make_memoryless_pls_texture r_146
#define make_pipeline_state r_147
#define mapBuffer r_148
#define mapped r_149
#define math r_14a
#define matrix r_14b
#define midpoint r_14c
#define onBeginFrame r_14d
#define onFlush r_14e
#define onMapBuffer r_14f
#define onUnmapAndSubmitBuffer r_150
#define outset r_151
#define pad r_152
#define paddingVertexCount r_153
#define paintData r_154
#define paintType r_155
#define params r_156
#define pathBufferRing r_157
#define pathID r_158
#define pathIDGranularity r_159
#define pathIdx r_15a
#define pathutils r_15b
#define pls r_15c
#define pop_front_n r_15d
#define programFeatures r_15e
#define pushContour r_15f
#define pushCubic r_160
#define pushInternalPathBatch r_161
#define pushPath r_162
#define push_back_n r_163
#define rawPath r_164
#define readFramebufferID r_165
#define reservePathData r_166
#define resize r_167
#define resizeAndRewind r_168
#define rive_pls_ios_metallib r_169
#define rive_pls_ios_metallib_len r_16a
#define rive_pls_macosx_metallib r_16b
#define rive_pls_macosx_metallib_len r_16c
#define segmentCounts r_16d
#define set r_16e
#define setClipContentID r_16f
#define setGradient r_170
#define setTargetTexture r_171
#define set_back r_172
#define shader r_173
#define shadowBuffer r_174
#define simple_chop_key r_175
#define stops r_176
#define strokeRadius r_177
#define strokesDisabled r_178
#define style r_179
#define style_flags r_17a
#define styled_verb r_17b
#define submit r_17c
#define submitTexels r_17d
#define submittedBuffer r_17e
#define submittedBufferIdx r_17f
#define submittedComplexColorRampCount r_180
#define submittedGradSpanCount r_181
#define submittedTexture r_182
#define submittedTextureID r_183
#define targetTexture r_184
#define tessSpanBufferRing r_185
#define tessTexWidthLog2_pathIDGranularity r_186
#define tessellate r_187
#define tessellateUniformBufferRing r_188
#define thickness r_189
#define type_gl r_18a
#define uniformBufferRing r_18b
#define uniqueKey r_18c
#define unmapAndSubmitBuffer r_18d
#define vertexDiscardValue r_18e
#define vertexIndex0 r_18f
#define viewportHeight r_190
#define viewportWidth r_191
#define widthInItems r_192
#define widthInTexels r_193
#define wireframe r_194
#define wrapGLRenderTarget r_195
#define x0x1 r_196
