/* eslint-disable @typescript-eslint/explicit-function-return-type */

/* global addToLibrary */

const LibraryWebGPUExtensions = {
    wgpuWagyuAdapterGetBackend: undefined,
    wgpuWagyuAdapterGetExtensions: undefined,
    wgpuWagyuAdapterGetGraphicsReport: undefined,
    wgpuWagyuAdapterGetName: undefined,
    wgpuWagyuAdapterRequestDeviceSync: undefined,
    wgpuWagyuCommandEncoderBlit: undefined,
    wgpuWagyuCommandEncoderGenerateMipmap: undefined,
    wgpuWagyuDeviceClearPipelineBinaryCache: undefined,
    wgpuWagyuDeviceEnableImaginationWorkarounds: undefined,
    wgpuWagyuDeviceGetExtensions: undefined,
    wgpuWagyuDeviceFlush: undefined,
    wgpuWagyuDeviceImportExternalTexture: undefined,
    wgpuWagyuDeviceIntrospectShaderCode: undefined,
    wgpuWagyuDevicePopulatePipelineBinaryCache: undefined,
    wgpuWagyuExternalTextureAddRef: undefined,
    wgpuWagyuExternalTextureRelease: undefined,
    wgpuWagyuExternalTextureSetLabel: undefined,
    wgpuWagyuInstanceEnableImaginationWorkarounds: undefined,
    wgpuWagyuInstanceGetApiVersion: undefined,
    wgpuWagyuInstanceGetBackend: undefined,
    wgpuWagyuInstanceGetExposeWGSLFeatures: undefined,
    wgpuWagyuInstanceGetRelaxedCompliance: undefined,
    wgpuWagyuInstanceGetScreenDirectFormat: undefined,
    wgpuWagyuInstanceGetScreenIndirectFormat: undefined,
    wgpuWagyuInstanceGetSync: undefined,
    wgpuWagyuInstanceRequestAdapterSync: undefined,
    wgpuWagyuInstanceSetCommandBufferLimit: undefined,
    wgpuWagyuInstanceSetExposeWGSLFeatures: undefined,
    wgpuWagyuInstanceSetImmediate: undefined,
    wgpuWagyuInstanceSetRunBarriersOnIncoherent: undefined,
    wgpuWagyuInstanceSetStagingBufferCacheSize: undefined,
    wgpuWagyuInstanceSetSync: undefined,
    wgpuWagyuRelaxedComplianceAddRef: undefined,
    wgpuWagyuRelaxedComplianceRelease: undefined,
    wgpuWagyuRelaxedComplianceGetBufferClear: undefined,
    wgpuWagyuRelaxedComplianceGetTextureClear: undefined,
    wgpuWagyuRelaxedComplianceSetAll: undefined,
    wgpuWagyuRelaxedComplianceSetBufferClear: undefined,
    wgpuWagyuRelaxedComplianceSetTextureClear: undefined,
    wgpuWagyuRenderBundleEncoderClearColorAttachments: undefined,
    wgpuWagyuRenderBundleEncoderClearDepthAttachment: undefined,
    wgpuWagyuRenderBundleEncoderClearStencilAttachment: undefined,
    wgpuWagyuRenderBundleEncoderSetScissorRect: undefined,
    wgpuWagyuRenderBundleEncoderSetScissorRectIndirect: undefined,
    wgpuWagyuRenderBundleEncoderSetViewport: undefined,
    wgpuWagyuRenderBundleEncoderSetViewportWithDepthIndirect: undefined,
    wgpuWagyuRenderBundleEncoderSetViewportWithoutDepthIndirect: undefined,
    wgpuWagyuRenderPassEncoderClearColorAttachments: undefined,
    wgpuWagyuRenderPassEncoderClearDepthAttachment: undefined,
    wgpuWagyuRenderPassEncoderClearStencilAttachment: undefined,
    wgpuWagyuRenderPassEncoderSetShaderPixelLocalStorageEnabled: undefined,
    wgpuWagyuRenderPassEncoderExecuteBundle: undefined,
    wgpuWagyuShaderEntryPointArrayFreeMembers: undefined,
    wgpuWagyuShaderModuleDestroy: undefined,
    wgpuWagyuShaderModuleIntrospect: undefined,
    wgpuWagyuStringArrayFreeMembers: undefined,
    wgpuWagyuStringViewFreeMembers: undefined,
    wgpuWagyuSurfaceDestroy: undefined,
    wgpuWagyuSurfaceGetCurrentDepthStencilTexture: undefined,
    wgpuWagyuSurfaceGetHeight: undefined,
    wgpuWagyuSurfaceGetWidth: undefined,
    wgpuWagyuSurfaceGetX: undefined,
    wgpuWagyuSurfaceGetY: undefined,
    wgpuWagyuSurfacePresent: undefined,
    wgpuWagyuSurfaceSetHeight: undefined,
    wgpuWagyuSurfaceSetWidth: undefined,
    wgpuWagyuSurfaceSetX: undefined,
    wgpuWagyuSurfaceSetY: undefined,
    wgpuWagyuWGSLFeatureTypeArrayFreeMembers: undefined,
};

addToLibrary(LibraryWebGPUExtensions);
